import {
  faDeleteLeft,
  faDivide,
  faEquals,
  faMinus,
  faPlus,
  faStarOfLife,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";
import Button from "./Button";

export default function ButtonGroup({
  inputHandler,
  deleteHandler,
  tambah,
  kurang,
  kali,
  bagi,
  jumlahkan,
  resetDisplay,
}) {
  return (
    <div className="mt-20 mx-auto grid grid-cols-4 sm:gap-x-10 lg:gap-x-3 lg:mt-4 lg:px-4  gap-x-6">
      <Button
        inputHandler={resetDisplay}
        color={"text-slate-400"}
        bg="bg-button2"
        height={16}
        text={"Ac"}
      />
      <Button
        inputHandler={deleteHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        height={16}
        text={<FontAwesomeIcon icon={faDeleteLeft} size={"sm"} />}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        simbol={"/"}
        text={"/"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        simbol={"*"}
        text={"*"}
      />

      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"7"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"8"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"9"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        simbol={"-"}
        text={"-"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"4"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"5"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"6"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        simbol={"+"}
        text={"+"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"1"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"2"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"3"}
      />
      <div
        onClick={jumlahkan}
        className={`p-4  cursor-pointer  hover:scale-110 active:bg-blue-500 duration-300 transition ease-in-out text-3xl button text-slate-400 shadow-sm bg-button2 mb-4 row-span-3`}
      >
        =
      </div>

      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"00"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button1"
        text={"0"}
      />
      <Button
        inputHandler={inputHandler}
        color={"text-slate-400"}
        bg="bg-button2"
        text={","}
      />
    </div>
  );
}
